# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

before_install:
  - ./test/customize_environment.sh

install:
  - ./src/setup.sh --full

language: generic

matrix:
  include:
    - os: linux
      dist: trusty

notifications:
  email:
    on_failure: always
    on_success: never

script:
  - ./test/sc.sh

sudo: required
