#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

  local CURRENT_DIRECTORY
  CURRENT_DIRECTORY="$(pwd)"

  declare -r -a FILES_TO_SOURCE=(
    "bash_aliases"
    "bash_autocomplete"
    "bash_colors"
    "bash_exports"
    "bash_functions"
    "bash_options"
    "bash_prompt"
  )

  local file=""
  local i=""

  for i in ${!FILES_TO_SOURCE[*]}; do

      file="$HOME/.${FILES_TO_SOURCE[$i]}"

      [ -r "$file" ] && . "$file"

  done

  cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

# clear
# echo -e "Logged in as $(whoami) at $(date -R)\n"
