#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create new directories and enter the first one.

mkd() {
  if [ -n "$*" ]; then
    mkdir -p "$@"

    cd "$1"

    return $?
  fi
}

# Quickly change to Windows profile
win() {
  local p
  p="/mnt/c/Users/$(whoami)"


  if [ -d "$p" ]; then
    cd "$p"
  fi
}
